services:
  atlas:
    build: .
    container_name: atlas
    working_dir: /app

    volumes:
      - .:/app

    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPATH: "/app"

    stdin_open: true
    tty: true

    command: bash
